# Generated by Django 4.1.4 on 2022-12-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Insti",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(blank=True, db_column="Code", null=True)),
                (
                    "institution",
                    models.TextField(blank=True, db_column="Institution", null=True),
                ),
                ("type", models.TextField(blank=True, db_column="Type", null=True)),
                (
                    "moharea",
                    models.TextField(blank=True, db_column="MOHArea", null=True),
                ),
                (
                    "pollingdivision",
                    models.TextField(
                        blank=True, db_column="PollingDivision", null=True
                    ),
                ),
                (
                    "instisinhala",
                    models.TextField(blank=True, db_column="InstiSinhala", null=True),
                ),
                (
                    "institutetelno",
                    models.TextField(blank=True, db_column="InstituteTelNo", null=True),
                ),
            ],
            options={
                "db_table": "insti",
                "managed": False,
            },
        ),
    ]
