# Generated by Django 4.1.4 on 2022-12-10 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MOHArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "district",
                    models.CharField(
                        choices=[("PU", "PU"), ("KU", "KU")], max_length=2
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PollingDivision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "district",
                    models.CharField(
                        choices=[("PU", "PU"), ("KU", "KU")], max_length=2
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=4, null=True)),
                ("institution_name", models.CharField(max_length=30)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BHA", "BHA"),
                            ("BHB", "BHB"),
                            ("DHA", "DHA"),
                            ("DHB", "DHB"),
                            ("DHC", "DHC"),
                            ("PMCU", "PMCU"),
                            ("UNIT", "UNIT"),
                            ("SDC", "SDC"),
                            ("ADC", "ADC"),
                            ("MOH", "MOH"),
                            ("PGH", "PGH"),
                            ("ELSE", "ELSE"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        choices=[("PU", "PU"), ("KU", "KU")], max_length=2
                    ),
                ),
                (
                    "sinhala_name",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("tel_no", models.CharField(blank=True, max_length=10, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "moh_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="institutions.moharea",
                    ),
                ),
                (
                    "polling_divition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="institutions.pollingdivision",
                    ),
                ),
            ],
        ),
    ]
